// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FButton: typeof import('./src/common/components/FButton.vue')['default']
    FButtonIcon: typeof import('./src/common/components/FButtonIcon.vue')['default']
    FCheckbox: typeof import('./src/inputs/components/FCheckbox.vue')['default']
    FCheckboxMultiple: typeof import('./src/inputs/components/FCheckboxMultiple.vue')['default']
    FCheckboxSingle: typeof import('./src/inputs/components/FCheckboxSingle.vue')['default']
    FChip: typeof import('./src/common/components/FChip.vue')['default']
    FColor: typeof import('./src/inputs/components/FColor.vue')['default']
    FControlHintMessage: typeof import('./src/common/components/FControlHintMessage.vue')['default']
    FControlLabel: typeof import('./src/common/components/FControlLabel.vue')['default']
    FControlWrap: typeof import('./src/common/components/FControlWrap.vue')['default']
    FDeleteConfirmationModal: typeof import('./src/common/components/FDeleteConfirmationModal.vue')['default']
    FFilter: typeof import('./src/filters/components/FFilter.vue')['default']
    FForm: typeof import('./src/forms/components/FForm.vue')['default']
    FFormFooter: typeof import('./src/forms/components/FFormFooter.vue')['default']
    FFormHeader: typeof import('./src/forms/components/FFormHeader.vue')['default']
    FFormMain: typeof import('./src/forms/components/FFormMain.vue')['default']
    FInput: typeof import('./src/inputs/components/FInput.vue')['default']
    FInputDate: typeof import('./src/inputs/components/FInputDate.vue')['default']
    FInputFile: typeof import('./src/inputs/components/FInputFile.vue')['default']
    FInputFilePreview: typeof import('./src/inputs/components/FInputFilePreview.vue')['default']
    FInputPassword: typeof import('./src/inputs/components/FInputPassword.vue')['default']
    FModal: typeof import('./src/common/components/FModal.vue')['default']
    FModalCard: typeof import('./src/common/components/FModalCard.vue')['default']
    FNotification: typeof import('./src/notifications/components/FNotification.vue')['default']
    FNotificationGroup: typeof import('./src/notifications/components/FNotificationGroup.vue')['default']
    FPagination: typeof import('./src/tables/components/FPagination.vue')['default']
    FProgressBar: typeof import('./src/common/components/FProgressBar.vue')['default']
    FRadio: typeof import('./src/inputs/components/FRadio.vue')['default']
    FSelect: typeof import('./src/inputs/components/FSelect.vue')['default']
    FSelectOptions: typeof import('./src/inputs/components/FSelectOptions.vue')['default']
    FTable: typeof import('./src/tables/components/FTable.vue')['default']
    FTableBody: typeof import('./src/tables/components/FTableBody.vue')['default']
    FTableFooter: typeof import('./src/tables/components/FTableFooter.vue')['default']
    FTableHeader: typeof import('./src/tables/components/FTableHeader.vue')['default']
    FTableRowActions: typeof import('./src/tables/components/FTableRowActions.vue')['default']
    FTableRowFilePreview: typeof import('./src/tables/components/FTableRowFilePreview.vue')['default']
    FTextarea: typeof import('./src/inputs/components/FTextarea.vue')['default']
  }
}
